GET http://localhost:8081/api/users

###

GET  http://localhost:8081/api/users/1

###

POST http://localhost:8081/api/users
Content-Type: application/json

{}

###

PUT http://localhost:8081/api/users/1
Content-Type: application/json

{}

###

PATCH  http://localhost:8081/api/users/1
Content-Type: application/json

{}


###

DELETE  http://localhost:8081/api/users/1
Content-Type: application/json

{}